version: '3.2'

# This compose file demonstrates how Ilmomasiina could be run in a production environment.

# This compose file serves Ilmomasiina at http://localhost:8000.
# Env variables from .env file (in the repository root) will be used by docker compose and passed to the container.
# Remember to create your own .env file (see .env.example)!

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE

  ilmomasiina:
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: always
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - NODE_ENV=production
      - ENFORCE_HTTPS=false
      # When deploying to production, either set ENFORCE_HTTPS true (default) or
      # configure the reverse proxy to enforce HTTPS communication with the clients.
    env_file:
      - .env
    ports:
      - "8000:3000"
    volumes:
    - "frontend:/opt/ilmomasiina/frontend"

volumes:
  frontend:
    # Contains static files of the ilmomasiina-frontend.
    # To achieve better performance under high loads, these files
    # can be served using a more performant web server or even a CDN.
