name: Publish Docker image

on:
  push:
    branches:
      - prod
      - staging
    tags:
      - 'v*'

jobs:
  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/tietokilta/ilmomasiina
          flavor: |
            latest=${{ github.ref == 'refs/heads/prod' }}
          tags: |
            type=semver,pattern={{version}},enable=${{ github.ref_type == 'tag' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.ref_type == 'tag' }}
            type=ref,event=branch,enable=${{ github.ref_type == 'branch' }}
            type=sha
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANDING_HEADER_TITLE_TEXT=Tietokillan ilmomasiina
            BRANDING_FOOTER_GDPR_TEXT=Tietosuoja
            BRANDING_FOOTER_GDPR_LINK=https://tietokilta.fi/kilta/hallinto/viralliset-asiat/rekisteriselosteet/
            BRANDING_FOOTER_HOME_TEXT=Tietokilta.fi
            BRANDING_FOOTER_HOME_LINK=https://tietokilta.fi

  npm:
    name: Publish JS packages
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        uses: pnpm/action-setup@v2
        with:
          version: 7
      -
        name: Setup Node.js for NPM
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '16'
          cache: 'pnpm'
      -
        name: Install dependencies
        run: |
          npm install -g pnpm@7
          pnpm install --frozen-lockfile --ignore-scripts
      -
        name: Build packages
        run: |
          pnpm run --filter @tietokilta/ilmomasiina-models build
          pnpm run --filter @tietokilta/ilmomasiina-components build
      -
        name: Publish to NPM
        run: |
          pnpm publish --filter @tietokilta/ilmomasiina-models --no-git-checks --access public
          pnpm publish --filter @tietokilta/ilmomasiina-components --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      -
        name: Publish to GitHub Packages
        run: |
          pnpm publish --filter @tietokilta/ilmomasiina-models --no-git-checks --access public
          pnpm publish --filter @tietokilta/ilmomasiina-components --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Push update to App Service
    needs: docker
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    environment: production
    steps:
    -
      name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    -
      uses: azure/webapps-deploy@v2
      with:
        app-name: tik-ilmo-${{ github.ref_name }}-app
        images: 'ghcr.io/tietokilta/ilmomasiina:${{ github.ref_name }}'
